import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <nav className="bg-gray-200 text-gray-900">
            <div className="container mx-auto py-4">NavBar</div>
          </nav>
          <main className="h-screen w-full bg-gray-100 text-gray-900">
            {children}
          </main>
          <footer className="p-3">Footer All rights reserved</footer>
        </section>
      </body>
    </html>
  );
}
